repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: ['--line-length', '120']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          [
            '--line-length=88',
            '--use-parentheses',
            '--trailing-comma',
            '--multi-line=3',
            '--profile',
            'black',
            '--line-length',
            '120'
          ]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args: ['--ignore=B006,B007,B008,B034,E203,E401,E402,E501,F401,W503']
